### ISSUE TITLE
Should a CI/CD pipeline stack be part of the scope here?

### ISSUE THREAD

**Issue by tiagostutz** [flaviostutz/docker-swarm-cluster#1]
Do you think this spec here should be opiniated about a CI/CD pipeline?
I mean, that’s not something you must have in order to use this stack, but it is something nice to have.
Maybe a “Nice to have” session where we could put something like CI/CD, Bots integration, Backup routines, and so on...

What are your thoughts on this?

**Comment by flaviostutz** [comment]
Great. What are your thoughts about that CI/CD pipeline?
By the way, I updated the TODO list https://github.com/flaviostutz/docker-swarm-cluster/commit/0bc87ab3e1b09d6a2d91a4886eb6844bbed24843

**Comment by tiagostutz** [comment]
Just a way to integrate the running cluster to an existing repo. We could start with GitLab, so we would have the Docker registry already integrated with the repo.
We could specify everthing needed for a source code `push` trigger a CI/CD pipeline from building the package until runnint it.

**Comment by tiagostutz** [comment]
As you put GitLab in the TODO list, I'm closing it here.

closes #1
