### ISSUE TITLE
docker-swarm-feeds and caddy

### ISSUE THREAD

**Issue by UnclePhil** [flaviostutz/docker-swarm-cluster#6]
Hello, I see you are still using this (flaviostutz/docker-swarm-feeds:1.1.0) version of feed with the caddy configuration.
For me feeds is dedicated to traefik 
Is it still working with caddy ??  ( I' ve a nice white  screen on my infra) 
or did you have plan to change the sniffing of the labels ?? 

But the idea to use it with caddy is very nice . just missing a traffic dashboard

Best regards 

Ph Koenig

**Comment by flaviostutz** [comment]
I don’t have plans to implemente this for Caddy now, but would be glad if you collaborate on this!
The implementation idea would be the same as with Traefik :)

Thanks for the interest!

**Comment by UnclePhil** [comment]
I'm working on it !!
Ability to use a more agnostic tag working with any container deployment and with a more customizable output interface (handlebar template usage)

**Comment by flaviostutz** [comment]
Great!

**Comment by UnclePhil** [comment]
First release!!, 
have a look and give some advice

https://github.com/UnclePhil/xfeed

Best regards
Ph Koenig
